### ISSUE TITLE
Presentation tidy ups for the slide in/slide out menu 

### ISSUE THREAD

**Issue by utunga** [CashlessSociety/cashless-ui#111]
A couple of outstanding issues from #21

**TODO:**

- [ ] All of this happens on all screen widths
- [ ] add space between icon and text in navbar links (so the + isn't right up against the POST)
- [ ] fix spacing/layout of navbar elements in navbar (get the right-aligned bits to right-align!)
- [ ] darken main body of site (maybe div id 'bodyClick') when sidebar open

Mockups that  show the hamburger menu / toggling slide out menu:

![toggle nav menu.png](https://images.zenhubusercontent.com/5b3abae1af2e4e3c8d3cb96a/9a65849b-e318-4bed-b4ff-e6164d3c88e5)

![hamburger-menu-mobile.gif](https://images.zenhubusercontent.com/5b3abae1af2e4e3c8d3cb96a/7d074fe0-0473-46ac-a44a-106b30e078e6)![hamburger-menu-desktop.gif](https://images.zenhubusercontent.com/5b3abae1af2e4e3c8d3cb96a/f72de010-84c1-4f19-b103-a21045292ce1)

[Go to Figma frame](https://www.figma.com/file/sq4aGgw7IQAbuRkXcFTaap/Cashless?node-id=1276%3A27135)
