### ISSUE TITLE
as anon I can sign in via google and recover access to my feed key from ... somewhere

### ISSUE THREAD

**Issue by utunga** [CashlessSociety/cashless-ui#28]
### Acceptance Criteria

- [ ] Clicking sign in with Google directs the user through the standard google process
- [ ] At end of Gmail Sign In a message is generated asserting gmail<->feed key assoc (saved to local storage but not posted as a message yet) 
- [ ] At end of Gmail Sign In a message is signed that indicates that the server node (ie @cashless.social) asserts the same gmail<->feed key assoc, as signd message using the current private key of the server node (also saved to local storage on client side)
- [ ] When the user authenticates as google they get hoisted <somehow> to sufficient crypto privileges to decrypt recover their private key (should it involve the message above?)

**Comment by DAHuerta** [comment]
Hey @utunga , I think we should reference #7 again. Does this need to be revisited because of the decision to not use Google Auth?

**Comment by utunga** [comment]
Yeah this is another one in the 'backlog' .. 

The idea was to have one card to *at a later stage* enable 'sign up via google' and then this card, separately, which is basically **log in via google**.

For what its worth (and.i know you didnt ask) but the tricky thing being that you need retrieve access to your private feedkey (that lets you post as 'you') and that makes some of us crypto people feel a bit nervous but really its no different than how we allow sites to control whether or not you can 'login' to their service or not.. the self soverign thing of being able to post without even needing to go to our website is a cool future feature but we dont want enabling that as an *option* to get in the way of keeping things 'easy to use' for the average person.
