### ISSUE TITLE
As an email recipient I can authenticate using a 'login' button in my email

### ISSUE THREAD

**Issue by utunga** [CashlessSociety/cashless-ui#33]
![email-link-authenticate.gif](https://images.zenhubusercontent.com/5b3abae1af2e4e3c8d3cb96a/6376a2d5-396f-42ab-86b8-49197e22a6f1)

[Desktop Prototype](https://www.figma.com/proto/sq4aGgw7IQAbuRkXcFTaap/Cashless?node-id=1116%3A204&viewport=813%2C-407%2C0.17307263612747192&scaling=min-zoom) | [Figma frame](https://www.figma.com/proto/sq4aGgw7IQAbuRkXcFTaap/Cashless?node-id=1116%3A210&viewport=813%2C-407%2C0.17307263612747192&scaling=min-zoom)

[Mobile Prototype](https://www.figma.com/proto/sq4aGgw7IQAbuRkXcFTaap/Cashless?node-id=1116%3A210&viewport=813%2C-407%2C0.17307263612747192&scaling=min-zoom) | [Figma frame](https://www.figma.com/file/sq4aGgw7IQAbuRkXcFTaap/Cashless?node-id=1116%3A210)

---

## Acceptance criteria

- [x] Whenever I am signed in via the key stored in local storage, but I *havent* yet sent myself an email, I am constantly reminded via a 'TOAST' in the top that i really ought to do that

- [x] When I click the Toast I am taken to a page suggesting ways I can save my feed key

- [x] I can fill in my email address and hit send

- [x] Hitting send sends an email to the given address with a login button

- [x] Clicking link in email takes me directly into the site as a 'user' (aka user-with-feed-key)

- [ ] Shortly after hitting Send I get a notification (Green tick?) indicating that email was sent (we dont know if received)

- [x] Once I have signed in via email at least once, the toast goes away in future

- [x] Having clicked the link in email the sign in stays very persistent on that device

**Comment by utunga** [comment]
Hmm so confused by what happens if we merge this now in terms of @karenkun  or @sarah-arrrgh  making further changes to the styling and stuff off tihs branch.

You know I guess maybe I just dont need to sweat it - maybe if Karen or whoever makes branch for all theri stuff off of tihs branch  shit then either:
- we merge back to main  and you can  can make a new PR to main .
or
- ..or  we don't merge yet and then *you can just make a merge to the epic/auth_flow branch. 

Sorry I guess you were probably going to do that anyway?

**Comment by luandro** [comment]
I say we merge to main, and branch from there. What u think?

**Comment by utunga** [comment]
We merged the first PR but this one still in 'in progress' until the designs are figured out. I will be adding issues for things we need to address.
