### ISSUE TITLE
as anon i can signup choose a name and profile and post things to my feed immediately

### ISSUE THREAD

**Issue by utunga** [CashlessSociety/cashless-ui#7]
### Acceptance Criteria

- [x] When not logged in there is a join button
- [x] When logged in there is *not* a join button
- [ ] Join button takes you to 'Join Cashless page, which looks like the design
- [x] Join button generates a new feed pub/priv key pair (which you can see in local storage) 
- [ ] You can upload an image and see a preview
- [x] You can set your name and have it 'ready' to save to your profile 
- [x] Clicking 'sign up' posts a message that 'saves' this data to your profile 
- [ ] HItting SignUp posts a *single* identity message asserting all three associations  [1] to the newly generated identity one-sided guid 
- [ ] After all this, if you do *not* hit sign up **nothing is posted to the feed and the feed itself is basically never created, or at least easily spotted later as being the empty set.
- [ ] If you somehow click on 'sign up' when you already have a feed key accessible you are directed to signed-in view of home page (which has no 'sign up' button) 

[1]
 - name is guid
 - profileSrcImg is guid
 - feedkey is guid
  
### Current designs

Join screens: https://www.figma.com/file/sq4aGgw7IQAbuRkXcFTaap/Cashless?node-id=933%3A376

- [Desktop Prototype](https://www.figma.com/proto/sq4aGgw7IQAbuRkXcFTaap/Cashless?node-id=900%3A19011&viewport=938%2C164%2C0.23830285668373108&scaling=min-zoom)
- [Mobile Prototype](https://www.figma.com/proto/sq4aGgw7IQAbuRkXcFTaap/Cashless?node-id=933%3A677&viewport=938%2C164%2C0.23830285668373108&scaling=min-zoom)

### Design shots 

NB: Screenshots may be out of date check above for definitive..

![image](https://user-images.githubusercontent.com/166867/106586574-803a8b00-65ad-11eb-87a3-d73793d87c8b.png)

**Comment by utunga** [comment]
@karenkun I'm really thinking we should take the google authentication aspect *out* of this user story ... **if you agree** lets move it back to.. uh.. "ready for design" ...  so you can make that change visually? 

**Then** maybe I add another user story for authenticating via google 

This is because
(a) authenticating by google is a 'nice to have'
(b) from a dev perspective its quite a bit more complex to have to add that as well

**Comment by karenkun** [comment]
So just to confirm, if we remove the Google Auth then the user can only login using the magic link.

**Comment by utunga** [comment]
Yup... at least until we add it back but yes.

**Comment by DAHuerta** [comment]
Hey Miles can you reaccess the requirements of this ticket. According to the comments, it looks like there are some changes to how the users sign in.

**Comment by utunga** [comment]
@DAHuerta well spotted. For what it's worth I did try to update the acceptance criteria - at the top - to reflect the changed requirements from the requirements.

Specifically, dropping the requirement for a google login (or at least moving that to a different card). @karenkun commentwas  that its probably not too confusing to have a mockup that includes the future state with both options avialable, and just tell the programmer (which actually might end up being me??) to just not show the bit they haven't coded yet.

What do you think ... does that work? Or should we amaybe change the images?

**Comment by utunga** [comment]
We might need to add some restrictions around the profile image and the upload experience - maybe as a separate card. 

Just noting that the colony ux for something similar looks like this (note the restrictions on the profile image) 


<img width="322" alt="image" src="https://user-images.githubusercontent.com/166867/111015390-68a4bc80-840d-11eb-9e36-a7ae240e8a77.png">

<img width="956" alt="image" src="https://user-images.githubusercontent.com/166867/111015264-cedd0f80-840c-11eb-801f-35f47faa5806.png">

**Comment by utunga** [comment]
We merged the  PR but moving this epic back to 'in progress' until the designs are figured out and all the acceptance criteria checked and any other things we need to address sorted.. I will be adding issues for things we need to address.

**Comment by luandro** [comment]
This is basically done, just missing some UI work.

**Comment by utunga** [comment]
tagging you in on this @karenkun
