### ISSUE TITLE
EPIC: Use google auth to save/recover key

### ISSUE THREAD

**Issue by utunga** [CashlessSociety/cashless-ui#9]
### Acceptance Criteria

- [ ] Clicking sign in with Google directs the user through the standard google process
- [ ] At end of Gmail Sign In a message is generated asserting gmail<->feed key assoc (saved to local storage but not posted as a message yet) 
- [ ] At end of Gmail Sign In a message is signed that indicates that the server node (ie @cashless.social) asserts the same gmail<->feed key assoc, as signd message using the current private key of the server node (also saved to local storage on client side)
- [ ] When the user authenticates as google they get hoisted <somehow> to sufficient crypto privileges to decrypt recover their private key (should it involve the message above?)

**Comment by DAHuerta** [comment]
In issue #7 there has been some discussion around not using Google authentication. This ticket could be blocked.

**Comment by utunga** [comment]
Yeah. Per the discussion on #7  I split this epic out and then  moved this ticket (in zenhub) all the way to the left (to the 'backlog' column). Problem is though that information is not visible here in github (which is where I am as write this). 

I wonder if we might be better to just have issues and projects in github for now, keep things simple. It can be prety much fundamentally confusing flicking back and forth between them (but I also really the simplicity of just updating the discussion, for an issue - as we are doing here - in github).

![image](https://user-images.githubusercontent.com/166867/108507902-e0f0f400-731f-11eb-9781-f144b5f59832.png)
I dunno what do you think? @jwu910 @DAHuerta ?
